module.exports =  { 
    FIELD_NOT_CORRECT:"欄位未填寫正確",
    COURSE_NOT_FOUND: "課程不存在", 
    ALREADY_REGISTERED: "已經報名過此課程", 
    NO_CREDITS: "已無可使用堂數", 
    MAX_PARTICIPANTS_REACHED: "已達最大參加人數，無法參加", 
    CANCEL_FAILED: "取消失敗", 
    UPDATE_COURSE_FAILED:"更新課程失敗",
    ID_ERROR: "ID錯誤",
    DUPLICATE_DATA:"資料重複",
    DATEFORM_ERROR:"日期格式錯誤，請使用 ISO 8601 (YYYY-MM-DDTHH:mm:ss.sssZ",
    EMAILFORM_ERROR:"輸入信箱格式錯誤",
    EMAIL_IS_USED:"Email 已被使用",
    PASSWORD_ERROR:"密碼不符合規則，需要包含英文數字大小寫，最短8個字，最長16個字",
    PASSWORD_NOT_CORRECT:"密碼錯誤",
    PASSWORD_NOT_CHANGE:"新密碼不能與舊密碼相同",
    NEWPASSWORD_NOT_VALIDATE:"新密碼與驗證新密碼不一致",
    PASSWORD_UPDATE_FAIL:"更新密碼失敗",
    USER_NOT_FOUND:"使用者不存在",
    USERNAME_NOT_CHANGE:"使用者名稱未變更",
    USER_ISNOT_COACH:"使用者尚未成為教練",
    USER_ALREADY_COACH:"使用者已經是教練",
    UPDATE_USERPROFILE_ERROR:"更新使用者資料失敗",
    PROFILE_URL_ERROR:"大頭貼網址錯誤",
    PAGE_OR_PER_ERROR:"頁碼以及顯示筆數須大於0，請檢查輸入數值",
    COACH_NOT_FOUND:"找不到該教練"
}